### ISSUE TITLE
Error on Browser back

### ISSUE THREAD

**Issue by AlissonSteffens** [shahen94/react-medium-zoom#1]
when you go back using browser button, react-medium-zoom has an error.
It prevents the page to be loaded.
The error is in this code
```js
componentWillUnmount() {
    this.zoom.off('open', this.props.onOpen)
    this.zoom.off('closed', this.props.onClosed)
  }
```
Maybe you could just remove it to fix (that's what I did).

**Comment by shahen94** [comment]
Hi @AlissonSteffens, thanks for contribution.
Can you please open PR ? I'll merge it asap.

Thanks
